#!/usr/bin/env bash

# Script maling dari https://gist.github.com/ericmurphyxyz/37baa4c9da9d3b057a522f20a9ad6eba
# Script to clean pacman and paru (or your favorite aur helper) cache
# Based on scripts from albertored11 and luukvbaal
# https://gist.github.com/albertored11/bfc0068f4e43ca0d7ce0af968f7314db
# https://gist.github.com/luukvbaal/2c697b5e068471ee989bff8a56507142

SCRIPT_NAME="$(basename "$0")"

# Assuming paru is run by user with UID 1000:
user="$(id -nu 1000)"

# The location of the cache for your aur helper:
AUR_CACHE_DIR="/home/$user/.cache/paru/clone"

# Get all uninstalled packages cache directories for AUR helper:
AUR_CACHE_REMOVED="$(comm -23 \
    <(basename -a $(find "$AUR_CACHE_DIR" -mindepth 1 -maxdepth 1 -type d) | sort) \
    <(pacman -Qqm) | \
    xargs -r printf "$AUR_CACHE_DIR/%s\n")"
AUR_CACHE_REMOVED="$(printf "%s" "$AUR_CACHE_REMOVED")"

# Delete all uninstalled packages cache:
if [ -n "$AUR_CACHE_REMOVED" ]; then
    tput bold; tput setaf 3
    printf "\tRemoving AUR cache:\n"
    tput sgr0
    while IFS= read -r pkg; do
        basename "$pkg"
    done <<< "$AUR_CACHE_REMOVED"
    rm -rf $AUR_CACHE_REMOVED
fi

# Get all cache directories for AUR helper (without removed packages)
AUR_CACHE="$(\
    find "$AUR_CACHE_DIR" -maxdepth 1 -type d | \
    awk '{ print "-c " $1 }' | \
    tail -n +2)"

# Delete all uninstalled pacman packages, keep two latest versions for installed packages
tput bold; tput setaf 3
printf "\tRemoving all uninstalled pacman packages cache:\n"
paccache -ruk0
tput bold; tput setaf 3
printf "\tOnly keep current and last versions of all installed packages cache:\n"
paccache -rk2 -c "/var/cache/pacman/pkg" $(echo "$AUR_CACHE")

# Send notification
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

notify-send -a "$SCRIPT_NAME" -u "normal" -i "package-purge" \
    "Clear cache" \
    "Pacman and AUR packages cache are cleared"
