#!/bin/sh

# Umar's config for aliases in zsh

chusr="doas"

# Go into directory
alias \
	cdd="cd $HOME/.dotfiles" \
	cdcol="cd $HOME/Documents/College" \
	dolcol="dolphin $HOME/Documents/College & disown" \

# apps
alias \
	sshk="keychain $HOME/.ssh/id_rsa && source $HOME/.keychain/$HOSTNAME-sh" \
	walbg="wal -n -i $XDG_DATA_HOME/bg" \
	walr="wal -R" \


# Commands that are too long. Abbreviate them!
alias \
	fetch="fastfetch" \
	sdn="shutdown now" \
	hibernate="systemctl hibernate" \
	so="source" \
	soz="source $XDG_CONFIG_HOME/zsh/.zshrc" \
	soa="source $XDG_CONFIG_HOME/shell/aliasrc" \
	ss="cd $HOME/.local/bin && ls" \
	loc="locate" \
	bt="bluetoothctl" \
	SS="$chusr systemctl" \
	g="git" \
	gcl="git clone" \
	gst="git status" \
	gch="git checkout" \
	gadd="git add" \
	gcom="git commit" \
	gcomm="git commit -m" \
	gp="git push" \
	makecl="make clean" \
	makein="$chusr make install" \
	makeun="$chusr make uninstall" \
	remake="$chusr make clean uninstall && $chusr make clean install" \

# Config editing
alias \
	cfz="$EDITOR $XDG_CONFIG_HOME/zsh/.zshrc" \
	cfzp="$EDITOR $XDG_CONFIG_HOME/shell/profile" \
	cfa="$EDITOR $XDG_CONFIG_HOME/shell/aliasrc" \
	cfv="$EDITOR $XDG_CONFIG_HOME/$EDITOR/$EDITOR-vimscript/init.vim" \
	cfl="$EDITOR $XDG_CONFIG_HOME/lf/lfrc" \
	cfvl="cd $XDG_CONFIG_HOME/$EDITOR/lua && ls" \
	cfal="$EDITOR $XDG_CONFIG_HOME/alacritty/alacritty.yml" \
	cfb="$EDITOR $XDG_CONFIG_HOME/bspwm/bspwmrc" \
	cfsx="$EDITOR $XDG_CONFIG_HOME/sxhkd/sxhkdrc" \
	cfp="$EDITOR $XDG_CONFIG_HOME/polybar/config.ini" \
	cfd="$EDITOR $XDG_CONFIG_HOME/dunst/dunstrc" \
	cfsynaptics="$chusr $EDITOR /etc/X11/xorg.conf.d/70-synaptics.conf" \
	cfxinit="$EDITOR $XDG_CONFIG_HOME/x11/xinitrc" \
	cfxr="$EDITOR $XDG_CONFIG_HOME/x11/xresources" \

# Verbosity and settings that you pretty much just always are going to want.
alias \
	df="df -h" \
	du="du -h" \
# Common commands with certain options
alias \
	la="ls -a" \
	ll="ls -l" \
	lla="ll -al" \
	lsd="ls -D" \
	pin="pacman -S" \
	pup="pacman -Syu" \
	pss="pacman -Ss" \
	pq="pacman -Q" \
	pqs="pacman -Qs" \
	pqq="pacman -Qq" \
	prm="pacman -R" \
	prns="pacman -Rns" \
	# la="ls -A" \ # not supported by exa
	# lla="ll -Al" \ # not supported by exa


# $chusr not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="$chusr $command"
done; unset command

# Use neovim for vi if present.
[ -x "$(command -v nvim)" ] && alias vi="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# # $chusr not required for some system commands (changed for $chusr written above)
# for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
# 	alias $command="$chusr $command"
# done; unset command

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	th="trash -v" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="exa --icons -h --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"
	# ls="exa -hN --color=auto --group-directories-first" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$VISUAL" \
	p="pacman" \
	xi="$chusr xbps-install" \
	xr="$chusr xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="$EDITOR -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
