#!/usr/bin/env sh

# This function is a wrapper for launching lf.
# When quitting from lf, the $PWD will be the current directory
# opened inside lf. This function is binded to ctrl-o.
lfcd() {
    ifinstalled lf lfub || exit 1
    tmp="$(mktemp -uq)"
    trap \
        'rm -f $tmp >/dev/null 2>&1 && trap - HUP INT QUIT TERM PWR EXIT' \
        HUP INT QUIT TERM PWR EXIT
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        directory="$(cat "$tmp")"
        [ -d "$directory" ] &&
            [ "$directory" != "$(pwd)" ] &&
                cd "$directory"
    fi
}

# Make directory and cd into it:
mkcd() {
    mkdir -pv "$1"
    cd "$1"
}
