#!/usr/bin/env zsh

# Umar's config for Zoomer Shell profile.
# Runs on login. Environmental variables are set here.

unsetopt PROMPT_SP

# # Add cursor theme:
# export XCURSOR_PATH=/usr/share/icons:$HOME/.icons:$HOME/.local/share/icons
# export XCURSOR_THEME="/home/umar/.icons/Posy_Cursor_Black_125_175"
# export XCURSOR_SIZE=

# Add local cloud directories:
export CLOUD_DIR="$HOME/Cloud"
export GDRIVE_UMAR="$CLOUD_DIR/gdrive-umar"
export GDRIVE_JASMINE="$CLOUD_DIR/gdrive-jasmine_belajar_id"
export ONEDRIVE_UMAR="$CLOUD_DIR/onedrive-umar"
export ONEDRIVE_BINUS="$CLOUD_DIR/onedrive-binus"

################################################################################

# Adds '~/.local/bin', '~/.dotfiles/scripts', '/usr/lib/gettext' to $PATH recursively:
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH="$PATH:${$(find ~/.dotfiles/scripts -type d -printf %p:)%%:}"
export PATH="$PATH:/usr/lib/gettext"

# Default programs:
export EDITOR="nvim"
export VISUAL="nvim"
export TERM="alacritty"
export TERMINAL="alacritty"
export BROWSER="brave"
export VIEWER="bat"
export VIDEO="mpv"
export IMAGE="nsxiv"
export COLORTERM="truecolor"
export PAGER="less"
export OPENER="xdg-open"
export WM="bspwm"

# XDG base directory:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"

# ~/ Clean-up:
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs, Does not work if using sddm as login manager
export XSERVERRC="$XDG_CONFIG_HOME/x11/xserverrc"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GEM_PATH="$XDG_DATA_HOME/ruby/gems"
export GEM_SPEC_CACHE="$XDG_DATA_HOME/ruby/specs"
export GEM_HOME="$XDG_DATA_HOME/ruby/gems"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GOPATH="$XDG_DATA_HOME/go"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# Ani-cli settings:
export ANI_CLI_MODE="sub"
export ANI_CLI_DOWNLOAD_DIR="$XDG_VIDEOS_DIR/Anime"
export ANI_CLI_QUALITY="best"
export ANI_CLI_PLAYER="mpv"
export ANI_CLI_EXTERNAL_MENU="0"
export ANI_CLI_MULTI_SELECTION="-m"
# export ANI_CLI_NON_INTERACTIVE=""
export ANI_CLI_HIST_DIR="$XDG_STATE_HOME/ani-cli"
export ANI_CLI_DEFAULT_SOURCE="history"

# Less colors:
# Reference (https://michurin.github.io/xterm256-color-picker) for color generation
# Start blinking:
    export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
# Start bold:
    export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
# Start standard out:
    # export LESS_TERMCAP_so="$(printf '%b' '[1;44;31m')"   # default Luke
    # export LESS_TERMCAP_so=$'\e''[38;5;160;48;5;228m'       # red on yellow
    export LESS_TERMCAP_so="$(tput bold; tput setaf 3)"     # yellow
# End standard out:
    export LESS_TERMCAP_se="$(printf '%b' '[0m')"
# Start underline:
    export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
# End underline:
    export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
# End bold, blinking, standard out, underline:
    export LESS_TERMCAP_me="$(printf '%b' '[0m')"

# # Additional colours for less and man (rest is in Luke's config):
# export LESS_TERMCAP_mr=$(tput rev)
# export LESS_TERMCAP_mh=$(tput dim)
# export LESS_TERMCAP_ZN=$(tput ssubm)
# export LESS_TERMCAP_ZV=$(tput rsubm)
# export LESS_TERMCAP_ZO=$(tput ssupm)
# export LESS_TERMCAP_ZW=$(tput rsupm)
# export GROFF_NO_SGR=1         # For Konsole and Gnome-terminal

# Scaling and theming:
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS="1;1;1"
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_QPA_PLATFORMTHEME="gtk2" # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm

# Create shortcuts if non existent:
[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] ||
    setsid shortcuts > /dev/null 2>&1

# Start graphical server on user's current tty if not already running:
# Comment it if using login manager.
[ "$(tty)" = "/dev/tty1" ] &&
    ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Switch escape and caps if tty and no password required:
sudo loadkeys "$HOME/.local/bin/sys/ttymaps.kmap" 2>/dev/null

# Nix profile:
[ -e "/home/umar/.nix-profile/etc/profile.d/nix.sh" ] &&
    source "/home/umar/.nix-profile/etc/profile.d/nix.sh"

# vim: filetype=zsh
