#!/usr/bin/env bash

# Script to encrypt and decrypt files and directories using gpg and 7z.

ifinstalled gpg 7z ||
    exit 1

# THC(Van Hausen)'s Secure Delete:
# SRM_PROG="srm"
# SRM_OPTS="-lr"

# GNU Shred from coreutils:
# SRM_PROG=shred
# SRM_OPTS="--remove=wipesync -f -n2"

# GPG Encryption options:
GPG_ENC_OPTS="--cipher-algo AES256 --compress-algo 0"

for file in "${@:2}" ; do
    dir=${file%/*}
    base="${file%.*}"
    ext="${file##*.}"

    mime_type=$(file -bh --mime-type "${file}")
    if [ "$mime_type" = "inode/directory" ]; then
        7z a "${file}.7z" "${file}"
        # ${SRM_PROG} ${SRM_OPTS} "$file"
        file="${file}.7z"
    fi

    case "$ext" in
        "gpg")
            gpg --decrypt --output "$base" "$file"
            # trash-put "$file"
            # rm -r "$file"
            ;;
        *)
            case "$1" in
                "unspecified")
                    gpg --encrypt ${GPG_ENC_OPTS} "$file"
                    ;;
                *)
                    gpg --encrypt --recipient "$1" ${GPG_ENC_OPTS} "$file"
                    ;;
            esac
            # ${SRM_PROG} ${SRM_OPTS} "$file"
            ;;
    esac
done
